name: dart_wom_connector
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http:
  encrypt: ^4.0.2
  dartz: ^0.9.1
  equatable:
  uuid: ^2.1.0
  geodesy: ^0.3.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.1
  mockito: ^4.1.1
