name: dart_wom_connector
description: Dart connector to the WOM platform.
version: 0.0.2-nullsafety.0
homepage: https://www.wom.social

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  encrypt: ^5.0.0
  equatable: ^2.0.3
  uuid: ^3.0.4
  geodesy: ^0.4.0-nullsafety.0
  meta: ^1.4.0
  pointycastle: ^3.1.3
  freezed_annotation:

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
  mockito: ^5.0.10
  build_runner:
  freezed:
  json_serializable: