name: dart_wom_connector
description: Dart connector to the WOM platform.
version: 0.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http:
  encrypt: ^4.0.2
  equatable:
  uuid: ^2.2.2
  geodesy: ^0.3.2
  meta:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.1
  mockito: ^4.1.1
