name: dart_wom_connector
description: Dart connector to the WOM platform.
version: 0.2.1
homepage: https://www.wom.social

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5
  encrypt: ^5.0.1
  equatable: ^2.0.3
  uuid: ^3.0.6
  geodesy: ^0.4.0-nullsafety.0
  meta: ^1.8.0
  pointycastle: ^3.6.1
  freezed_annotation: ^2.1.0

#dependency_overrides:
#  analyzer: 1.5.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.4
#  mockito: ^5.3.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

scripts: derry.yaml